version: '3.4'

services:
  ashley:
    build:
      context: .
      target: development
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: ashley:development
    environment:
      PYLINTHOME: /app/.pylint.d
    env_file:
      - env.d/development/common
    ports:
      - "8090:8000"
    volumes:
      - .:/app
