"""Factories for the ``ashley`` application."""
import json

import factory
from django.utils.text import slugify
from factory.django import DjangoModelFactory
from faker import Faker
from machina.core.db.models import get_model

from lti_provider.factories import LTIConsumerFactory

faker = Faker()

Forum = get_model("forum", "Forum")  # pylint: disable=C0103
LTIContext = get_model("ashley", "LTIContext")  # pylint: disable=C0103
Post = get_model("forum_conversation", "Post")  # pylint: disable=C0103
Topic = get_model("forum_conversation", "Topic")  # pylint: disable=C0103
User = get_model("ashley", "User")  # pylint: disable=C0103


class UserFactory(DjangoModelFactory):
    """Factory to create a User."""

    class Meta:
        model = User

    lti_consumer = factory.SubFactory(LTIConsumerFactory)

    public_username = factory.Sequence(lambda n: f"user{n}")
    email = factory.LazyAttribute(lambda u: f"{u.public_username}@example.com")
    lti_remote_user_id = factory.SelfAttribute("public_username")
    username = factory.LazyAttribute(
        lambda u: f"{u.public_username}@{u.lti_consumer.slug}"
    )


class LTIContextFactory(DjangoModelFactory):
    """Factory to create a LTIContext."""

    class Meta:
        model = LTIContext

    lti_consumer = factory.SubFactory(LTIConsumerFactory)
    lti_id = factory.Sequence(lambda n: f"context{n}")


class ForumFactory(DjangoModelFactory):
    """Factory to create a Forum"""

    class Meta:
        model = Forum

    type = Forum.FORUM_POST
    name = factory.Sequence(lambda n: f"forum{n}")


class TopicFactory(DjangoModelFactory):
    """Factory to create a Topic"""

    class Meta:
        model = Topic

    forum = factory.SubFactory(ForumFactory)
    poster = factory.SubFactory(UserFactory)
    status = Topic.TOPIC_UNLOCKED
    subject = factory.Faker("text", max_nb_chars=20)
    slug = factory.LazyAttribute(lambda t: slugify(t.subject))
    type = Topic.TOPIC_POST


class PostFactory(DjangoModelFactory):
    """Factory to create a Post"""

    class Meta:
        model = Post
        exclude = ("text",)

    text = factory.Faker("paragraph", nb_sentences=3)

    topic = factory.SubFactory(TopicFactory)
    poster = factory.SubFactory(UserFactory)
    subject = factory.Faker("text", max_nb_chars=20)

    @factory.lazy_attribute
    def content(self):
        """Building a fake content around the text as would be generated by draftjs."""
        data = {
            "blocks": [
                {
                    "key": faker.uuid4(),
                    "text": self.text,
                    "type": "unstyled",
                    "depth": 0,
                    "inlineStyleRanges": [],
                    "entityRanges": [],
                    "data": {},
                }
            ],
            "entityMap": {},
        }
        return json.dumps(data)
