#
# Your crowdin's credentials
#
"api_key_env": CROWDIN_API_KEY
"project_identifier_env": CROWDIN_PROJECT_ID
"base_path_env": CROWDIN_BASE_PATH

#
# Choose file structure in crowdin
# e.g. true or false
#
"preserve_hierarchy": false

#
# Files configuration
#
files: [
 {
  "source" : "/ashley/locale/django.pot",
  "dest": "/backend.pot",
  "translation" : "/ashley/locale/%locale_with_underscore%/LC_MESSAGES/django.po"
 },
 {
  source : "/frontend/i18n/frontend.json",
  dest: "/frontend.json",
  translation : "/frontend/i18n/locales/%locale_with_underscore%.json",
 }
]
