# Generated by Django 3.1.6 on 2021-02-15 15:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0013_lti_contexts_and_lti_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="lti_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
